### ISSUE TITLE
 {"detail":{"message":"Unauthorized - Invalid access token"}}

### ISSUE THREAD

**Issue by hunkjun** [moeakwak/chatgpt-web-share#109]
python 脚本使用access_token可以使用,说明accesstoken 是没问题的。
```
# python3 test.py "hello"
Hello! How may I assist you today?
```

使用token在cws中无法使用。报错
```
2023/04/17 16:47:45.739     INFO: [cws.main] Using <default_bypass> as ChatGPT base url
2023/04/17 16:47:45.739     INFO: [cws.utils.sync_conversations] Syncing conversations...
2023/04/17 16:47:48.176    ERROR: [cws.utils.sync_conversations] Fetch conversation error (ChatGPTError): OpenAI 401: {"detail":{"message":"Unauthorized - Invalid access token"}}
2023/04/17 16:47:48.176  WARNING: [cws.utils.sync_conversations] Sync conversations on startup failed!
```
是什么原因呢

**Comment by moeakwak** [comment]
尝试更新到最新版本看看

**Comment by hunkjun** [comment]
已更新到最新版本了，还是会报错.单独测试了下: 

```
/data # python3 test2.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 1175, in __check_response
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://chat.gateway.do/api/conversations?offset=0&limit=20'
For more information check: https://httpstatuses.com/401

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/test2.py", line 20, in <module>
    asyncio.run(c.get_conversations())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data/test2.py", line 15, in get_conversations
    conversations = await self.chatbot.get_conversations()
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 1098, in get_conversations
    await self.__check_response(response)
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 1183, in __check_response
    raise error from e
revChatGPT.typings.Error: OpenAI: {"detail":{"message":"Unauthorized - Invalid access token"}} (code: 401)
```

**Comment by moeakwak** [comment]
那就是access token有问题。建议在相同网络环境先登出，再登录，重新获取access token

**Comment by hunkjun** [comment]
嗯、从新获登录获取key也不行，但是从"LAST USED"看确实访问到了，可能是key的问题。

谢谢了。

**Comment by moeakwak** [comment]
我看你用的是公共代理，试试用自己的代理吧

**Comment by hunkjun** [comment]
我的机器在国外能不能不指定代理呢.（包括公共代理和自己的代理）

**Comment by ludashi2020** [comment]
自建代理：https://github.com/linweiyuan/go-chatgpt-api

**Comment by hunkjun** [comment]
https://chat.openai.com/api/auth/session 
https://platform.openai.com/account/api-keys

token 和 key 的区别是什么呢

目前程序只能用token 访问哇

**Comment by hunkjun** [comment]
> 自建代理：https://github.com/linweiyuan/go-chatgpt-api

好的，已经按这个做了，已经显示”Welcome to ChatGPT“了
非常感谢
