### ISSUE TITLE
Unable to deploy docker containner due to CHATGPT_BASE_URL

### ISSUE THREAD

**Issue by ggdxwz** [moeakwak/chatgpt-web-share#14]
```
Successfully started Caddy (pid=17) - Caddy is running in the background
Traceback (most recent call last):
  File "/app/backend/main.py", line 16, in <module>
    environ["CHATGPT_BASE_URL"] = config.get("chatgpt_base_url", environ.get("CHATGPT_BASE_URL"))
  File "/usr/local/lib/python3.10/os.py", line 685, in __setitem__
    value = self.encodevalue(value)
  File "/usr/local/lib/python3.10/os.py", line 757, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
```
不确定报错是不是由database_url引起的
config里面我没改任何东西，直接用的 `database_url: "sqlite+aiosqlite:////data/database.db"` 

V2看到的，项目真棒已star

**Comment by moeakwak** [comment]
抱歉，这个是因为requirements里面少了一个依赖，用来打印彩色的日志。马上修复，感谢支持

**Comment by moeakwak** [comment]
应该是修复了，请更新到 0.2.8 版本试试
