### ISSUE TITLE
语言模型缺少枚举类型 gpt-4-plugins

### ISSUE THREAD

**Issue by aodzip** [moeakwak/chatgpt-web-share#161]
**Version**
v0.3.15

**What's your deploying method?**
- [*] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
如果这个账号使用过gpt-4-plugins模型，后台大部分界面将崩溃

**To Reproduce**
1. 在chat.openai.com上新建一个基于plugins的对话
2. webshare后台的大部分页面将损坏

**Expected behavior**
无事发生

**Your config.yaml or other configurations**
用不上

**Screenshots or running logs**
```
2023/05/17 14:39:26.323    ERROR: [uvicorn.error]	Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'gpt-4-plugins'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 61, in __call__
    raise exc
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 58, in __call__
    await self.app(scope, receive, inner_send)
  File "/app/backend/api/middlewares/request_statistics.py", line 32, in __call__
    raise exc
  File "/app/backend/api/middlewares/request_statistics.py", line 30, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/backend/api/routers/chat.py", line 57, in get_all_conversations
    r = await session.execute(select(Conversation))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 313, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 256, in orm_execute_statement
    return cls.orm_setup_cursor_result(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 498, in orm_setup_cursor_result
    return loading.instances(result, querycontext)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 233, in instances
    _prebuffered = list(chunks(None))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 191, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 521, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 521, in <listcomp>
    return [make_row(row) for row in rows]
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 25, in sqlalchemy.cyextension.resultproxy.BaseRow.__init__
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1772, in process
    value = self._object_value_for_elem(value)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1655, in _object_value_for_elem
    raise LookupError(
LookupError: 'gpt-4-plugins' is not among the defined enum values. Enum name: chatmodels. Possible values: gpt-4, text-davinc.., text-davinc.., 
```

**Additional context**
不需要

**Comment by spldmanager** [comment]
已搞定，用sqlite3删除对应的conversation就好了
