### ISSUE TITLE
v0.4.0-alpha1 "connection refused"

### ISSUE THREAD

**Issue by maxduke** [moeakwak/chatgpt-web-share#175]
**Version**
v0.4.0-alpha1

**What's your deploying method?**
- [X ] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
yaml文件都是通过manage.py生成并调整。
用户登录时报错

logs：

```
chatgpt-share  | 2023/05/24 16:21:42.828     INFO: [uvicorn.error] Started server process [1]
chatgpt-share  | 2023/05/24 16:21:42.828     INFO: [uvicorn.error] Waiting for application startup.
chatgpt-share  | 2023/05/24 16:21:42.833     INFO: [alembic.runtime.migration] Context impl SQLiteImpl.
chatgpt-share  | 2023/05/24 16:21:42.833     INFO: [alembic.runtime.migration] Will assume non-transactional DDL.
chatgpt-share  | 2023/05/24 16:21:42.837     INFO: [cws.api.database.sqlalchemy] database initialized
chatgpt-share  | {"level":"error","ts":1684916530.427356,"logger":"http.log.error","msg":"dial tcp 127.0.0.1:8000: connect: connection refused","request":{"remote_ip":"172.21.11.1","remote_port":"58632","proto":"HTTP/1.1","method":"POST","host":"XXXXXX","uri":"/api/auth/login","headers":{"Referer":["https://XXXXX/login"],"X-Forwarded-Scheme":["https"],"X-Forwarded-Proto":["https"],"X-Forwarded-For":["XXXXXXX, 172.71.210.160"],"Cdn-Loop":["cloudflare"],"Accept-Encoding":["gzip"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\""],"Cf-Connecting-Ip":["XXXXXX"],"Content-Length":["251"],"Sec-Fetch-Site":["same-origin"],"Sec-Fetch-Dest":["empty"],"X-Real-Ip":["172.71.210.160"],"Cf-Ipcountry":["CN"],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Origin":["https://XXXXXX"],"Sec-Fetch-Mode":["cors"],"Accept-Language":["en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7"],"Cf-Ray":["7cc4211afa29105f-HKG"],"Accept":["application/json, text/plain, */*"],"Content-Type":["multipart/form-data; boundary=----WebKitFormBoundary31IINpV0ZGJgiAYK"],"Cookie":[]}},"duration":0.001768424,"status":502,"err_id":"vqsde2y2i","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
chatgpt-share  | 2023/05/24 16:22:13.075    ERROR: [uvicorn.error] Traceback (most recent call last):
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
chatgpt-share  |     async with self.lifespan_context(app) as maybe_state:
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
chatgpt-share  |     await self._router.startup()
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
chatgpt-share  |     await handler()
chatgpt-share  |   File "/app/backend/main.py", line 85, in on_startup
chatgpt-share  |     await init_mongodb()
chatgpt-share  |   File "/app/backend/api/database/mongodb.py", line 19, in init_mongodb
chatgpt-share  |     await init_beanie(database=client[DATABASE_NAME],
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 531, in init_beanie
chatgpt-share  |     await Initializer(
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 89, in __await__
chatgpt-share  |     yield from self.init_class(model).__await__()
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 501, in init_class
chatgpt-share  |     await self.init_document(cls)
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 324, in init_document
chatgpt-share  |     build_info = await self.database.command({"buildInfo": 1})
chatgpt-share  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
chatgpt-share  |     result = self.fn(*self.args, **self.kwargs)
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
chatgpt-share  |     return func(self, *args, **kwargs)
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/pymongo/database.py", line 805, in command
chatgpt-share  |     with self.__client._socket_for_reads(read_preference, session) as (
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1296, in _socket_for_reads
chatgpt-share  |     server = self._select_server(read_preference, session)
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1257, in _select_server
chatgpt-share  |     server = topology.select_server(server_selector)
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 272, in select_server
chatgpt-share  |     server = self._select_server(selector, server_selection_timeout, address)
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 261, in _select_server
chatgpt-share  |     servers = self.select_servers(selector, server_selection_timeout, address)
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 223, in select_servers
chatgpt-share  |     server_descriptions = self._select_servers_loop(selector, server_timeout, address)
chatgpt-share  |   File "/usr/local/lib/python3.10/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
chatgpt-share  |     raise ServerSelectionTimeoutError(
chatgpt-share  | pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -2] Name does not resolve, Timeout: 30s, Topology Description: <TopologyDescription id: 646dc916473e2a706cc65fec, topology_type: Unknown, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name does not resolve')>]>
chatgpt-share  |
chatgpt-share  | 2023/05/24 16:22:13.076    ERROR: [uvicorn.error] Application startup failed. Exiting.

**Comment by moeakwak** [comment]
你的mongodb url没有配置好，请自行解决配置问题
