### ISSUE TITLE
更新0.4.0-alpha4.3后，api访问错误 Request URL is missing an 'http://' or 'https://' protocol.

### ISSUE THREAD

**Issue by 6ccg** [moeakwak/chatgpt-web-share#211]
**Version**
[v0.4.0-alpha4.3]

**What's your deploying method?**
- [ x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
更新0,4,0-alpha4.3后，api访问错误。 无法打开会话，无法新建聊天，提示request error。日志显示“Request URL is missing an 'http://' or 'https://' protocol.”

在未修改其他环境配置的情况下，降到4.2后正常。api地址已经更新到http://go-chatgpt-api:8080/chatgpt/backend-api/conversation的新地址
**To Reproduce**

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**

```
2023/06/23 19:08:28.072  WARNING: [cws.api.routers.conv]	635bb414-b5a0-4364-8753-ae0a21e3be75 get conversation history failed: UnsupportedProtocol Request URL is missing an 'http://' or 'https://' protocol.
2023/06/23 19:08:28.077     INFO: [cws.access]	172.26.0.1:0 | GET /conv/635bb414-b5a0-4364-8753-ae0a21e3be75 HTTP/1.1 | 500 Internal Server Error | 26 ms
2023/06/23 19:08:28.080    ERROR: [uvicorn.error]	Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 214, in handle_async_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 61, in __call__
    raise exc
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 58, in __call__
    await self.app(scope, receive, inner_send)
  File "/app/backend/api/middlewares/request_statistics.py", line 59, in __call__
    raise exc
  File "/app/backend/api/middlewares/request_statistics.py", line 57, in __call__
    await self.app(scope, receive, send_with_inspecting_body)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/backend/api/routers/conv.py", line 96, in get_conversation_history
    raise e
  File "/app/backend/api/routers/conv.py", line 73, in get_conversation_history
    result = await openai_web_manager.get_conversation_history(conversation.conversation_id)
  File "/app/backend/api/sources/openai_web.py", line 190, in get_conversation_history
    response = await self.session.get(url, timeout=None)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
```
**Additional context**
附上docker-compose配置：

```
version: "3"

services:
  chatgpt-web-share:
    image: ghcr.io/moeakwak/chatgpt-web-share:0.4.0-alpha4.3  (这里降级成4.2就正常了)
    container_name: cwsa
    restart: unless-stopped
    ports:
      - 8092:80  #端口可调整
    volumes:
      - ./data:/app/backend/data
    environment:
      - TZ=Asia/Shanghai
      - CWS_CONFIG_DIR=/app/backend/data/config
      - CHATGPT_BASE_URL=http://go-chatgpt-api:8080/chatgpt/backend-api/
    depends_on:
      - mongo
      - go-chatgpt-api

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: xxxx
      MONGO_INITDB_ROOT_USERNAME: xxxx
      MONGO_INITDB_ROOT_PASSWORD: xxxx


  go-chatgpt-api:
    container_name: go-chatgpt-apia
    image: linweiyuan/go-chatgpt-api:latest
    environment:
      - GIN_MODE=release
    restart: unless-stopped
```

**Comment by moeakwak** [comment]
4.3配置字段有更改，在管理后台重新设置 base_url 即可

**Comment by V1V1rus** [comment]
请问老哥，现在能正常使用4.0吗？
OpenaiWebException: -1 {"detail":"Our systems have detected unusual activity from your system. Please try again later."}

**Comment by cmlibo** [comment]
配置有很大调整，参照代码，改成以下就可以了。我已经成功运行了
目前的问题在于原来的历史数据不兼容，导入到新的库还需要摸索
改配置
credentials.yaml
openai_web_access_token: "ey****"
openai_api_key: "sk-**"

config.yaml
openai_web:
  openai_base_url: https://api.openai.com/v1/
  chatgpt_base_url: http://****/chatgpt/backend-api/
  connect_timeout: 10
  read_timeout: 10
  is_plus_account: true
  ask_timeout: 600

**Comment by yanwen** [comment]
> 
@cmlibo 
这里： chatgpt_base_url: http://****/chatgpt/backend-api/

这个可以换成自己搭建的 http://go-chatgpt-api:8080/chatgpt/backend-api/  吗？？ 还是必须得用他们公开的接口？

**Comment by cmlibo** [comment]
> > 
> 
> @cmlibo 这里： chatgpt_base_url: http://****/chatgpt/backend-api/
> 
> 这个可以换成自己搭建的 http://go-chatgpt-api:8080/chatgpt/backend-api/ 吗？？ 还是必须得用他们公开的接口？

可以用自己的，注意下ip，不能localhost

**Comment by yanwen** [comment]
> > > 
> > 
> > 
> > @cmlibo 这里： chatgpt_base_url: http://****/chatgpt/backend-api/ 
> > 这个可以换成自己搭建的  [http://go-chatgpt-api:8080/chatgpt/backend-api/ ](http://go-chatgpt-api:8080/chatgpt/backend-api/) 吗？？ 还是必须得用他们公开的接口？
> 
> 可以用自己的，注意下ip，不能localhost

谢谢，解决了。不能go-chatgpt-api:8080 也不能127.0.0.1:8080 也不能用docker的那个内网 192.168.128.2:8080  。换成公网ip:8080  这样解决了。

感谢。

**Comment by cmlibo** [comment]
> localhost

可以用docker那个内网，前提是两个docker启动时是否配置了network参数，是不是在同一个里面，也可以用VPS的内网IP，实在不行就直接外网IP

**Comment by minchieh-fay** [comment]
一定要用go-chatgpt-api么
我那个服务器已经用wrap整机绕过cf了
没有go-chatgpt-api, 我就没设置chatgpt_base_url
然后就报错Request URL is missing an 'http://' or 'https://' protocol
