### ISSUE TITLE
admin 界面统计数据报错 undefined

### ISSUE THREAD

**Issue by zhboner** [moeakwak/chatgpt-web-share#216]
**Version**
v0.3.15

**What's your deploying method?**
- [*] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**
On admin panel, the system info shows undefined, and the web page says request error. 

**To Reproduce**
Go to 'admin panel'

**Expected behavior**
show statistics info

**Your config.yaml or other configurations**
![config.yaml](https://imgur.com/sSS84hG.jpg)

**Screenshots or running logs**
![screenshots](https://i.imgur.com/rGBDKA1.jpg)

### 日志
I guess that 500 error on line 3 and the python error are two different errors. Correct me if I am wrong.
 
```
2023/06/28 06:31:53.409     INFO: [cws.access]	172.18.0.1:0 | GET /user/me HTTP/1.1 | 200 OK | 11 ms
2023/06/28 06:31:53.716     INFO: [cws.access]	172.18.0.1:0 | GET /system/request_statistics HTTP/1.1 | 200 OK | 47 ms
2023/06/28 06:31:53.736     INFO: [cws.access]	172.18.0.1:0 | GET /system/info HTTP/1.1 | 500 Internal Server Error | 77 ms
2023/06/28 06:31:53.738    ERROR: [uvicorn.error]	Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'text-davinci-002-render-sha-mobile'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 61, in __call__
    raise exc
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 58, in __call__
    await self.app(scope, receive, inner_send)
  File "/app/backend/api/middlewares/request_statistics.py", line 32, in __call__
    raise exc
  File "/app/backend/api/middlewares/request_statistics.py", line 30, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/backend/api/routers/system.py", line 74, in get_system_info
    conversations = await session.execute(select(Conversation))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 313, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 256, in orm_execute_statement
    return cls.orm_setup_cursor_result(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 498, in orm_setup_cursor_result
    return loading.instances(result, querycontext)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 233, in instances
    _prebuffered = list(chunks(None))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 191, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 521, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 521, in <listcomp>
    return [make_row(row) for row in rows]
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 25, in sqlalchemy.cyextension.resultproxy.BaseRow.__init__
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1772, in process
    value = self._object_value_for_elem(value)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1655, in _object_value_for_elem
    raise LookupError(
LookupError: 'text-davinci-002-render-sha-mobile' is not among the defined enum values. Enum name: chatmodels. Possible values: gpt-4, text-davinc.., text-davinc.., 
2023/06/28 06:31:53.750     INFO: [cws.access]	172.18.0.1:0 | GET /user HTTP/1.1 | 200 OK | 81 ms
```

**Additional context**
 I am using a nginx as a reverse proxy

**Comment by moeakwak** [comment]
旧版本不支持 gpt 3.5 mobile 模型，请使用 alpha 版本。
