### ISSUE TITLE
在ChatGPT官网中使用了gpt-4-code-interpreter后 导致 chatgpt-web-share 无法使用gtp4了

### ISSUE THREAD

**Issue by shiguang3** [moeakwak/chatgpt-web-share#230]
**Version**
v0.3.15

**What's your deploying environment?**
- [* ] Docker
- [ ] Caddy
- [ ] Other

**Describe the problem**
在ChatGPT官网中使用了gpt-4-code-interpreter后 导致 chatgpt-web-share 无法使用gtp4了

![image](https://github.com/moeakwak/chatgpt-web-share/assets/48662444/27768c98-5d92-4d3b-88ef-84d8972a1590)

![image](https://github.com/moeakwak/chatgpt-web-share/assets/48662444/f729df11-9fb3-42f7-95de-79cbeba3bca0)
![image](https://github.com/moeakwak/chatgpt-web-share/assets/48662444/99b5364f-fcd2-46ba-be31-60179322bd69)

**Screenshots or running logs**

2023/07/12 11:02:56.723    ERROR: [uvicorn.error]	Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'gpt-4-code-interpreter'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 61, in __call__
    raise exc
  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 58, in __call__
    await self.app(scope, receive, inner_send)
  File "/app/backend/api/middlewares/request_statistics.py", line 32, in __call__
    raise exc
  File "/app/backend/api/middlewares/request_statistics.py", line 30, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/backend/api/routers/chat.py", line 57, in get_all_conversations
    r = await session.execute(select(Conversation))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 313, in execute
    result = await greenlet_spawn(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 256, in orm_execute_statement
    return cls.orm_setup_cursor_result(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 498, in orm_setup_cursor_result
    return loading.instances(result, querycontext)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 233, in instances
    _prebuffered = list(chunks(None))
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 191, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 521, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 521, in <listcomp>
    return [make_row(row) for row in rows]
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 25, in sqlalchemy.cyextension.resultproxy.BaseRow.__init__
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1772, in process
    value = self._object_value_for_elem(value)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 1655, in _object_value_for_elem
    raise LookupError(
LookupError: 'gpt-4-code-interpreter' is not among the defined enum values. Enum name: chatmodels. Possible values: gpt-4, text-davinc.., text-davinc..,

**Comment by yanwen** [comment]
亲自用了一下，并没有出现不可用的情况。还是能用的。不过我的版本是阿尔法4.4

**Comment by qshy** [comment]
> 亲自用了一下，并没有出现不可用的情况。还是能用的。不过我的版本是阿尔法4.4

请教下，OpenAI: {"errorMessage":"Failed to get arkose token."} (code: 403)
2023/08/24 11:39:44.029    DEBUG: [cws.api.routers.chat]	terminated ask None (ChatModels.gpt4) because of error
这个错误怎么解。是花了20刀付费用户。

**Comment by yanwen** [comment]
> > 亲自用了一下，并没有出现不可用的情况。还是能用的。不过我的版本是阿尔法4.4
> 
> 请教下，OpenAI: {"errorMessage":"Failed to get arkose token."} (code: 403) 2023/08/24 11:39:44.029 DEBUG: [cws.api.routers.chat] terminated ask None (ChatModels.gpt4) because of error 这个错误怎么解。是花了20刀付费用户。

403问题是因为GPT4模型需要 arkose token。跟你plus账号无关。
可以配合这个 https://github.com/xyhelper/xyhelper-arkose-v2 使用。

**Comment by update757** [comment]
https://github.com/xyhelper/xyhelper-arkose-v2 这个办法也不能获取arkose token了。
2023-09-09 02:16:10 2023/09/09 02:16:10.505    ERROR: [cws.api.routers.chat] OpenAI: {"errorMessage":"Failed to get arkose token."} (code: 403)

**Comment by spammenotinoz** [comment]
Should be closed, use of Code-Interpreter does not cause this problem.
Arkose token refresh and update is an existing requirement.
