### ISSUE TITLE
用户管理-添加新用户失败

### ISSUE THREAD

**Issue by Oliverwqcwrw** [moeakwak/chatgpt-web-share#365]
**Version**
v0.4.6-beta1

**What's your deploying method?**
- [x] Docker
- [ ] Caddy
- [ ] Other

**Describe the bug**

用户管理中添加新用户失败

**To Reproduce**

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
If applicable, add screenshots or logs to help explain your problem.

> 
                        ERROR: [uvicorn.error] Exception in ASGI application
                
                Traceback (most recent call last):
                  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
                    result = await app(  # type: ignore[func-returns-value]
                  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
                    return await self.app(scope, receive, send)
                  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
                    await super().__call__(scope, receive, send)
                  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
                    await self.middleware_stack(scope, receive, send)
                  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
                    raise exc
                  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
                    await self.app(scope, receive, _send)
                  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
                    await self.simple_response(scope, receive, send, request_headers=headers)
                  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
                    await self.app(scope, receive, send)
                  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 61, in __call__
                    raise exc
                  File "/app/backend/api/middlewares/asgi_logger/middleware.py", line 58, in __call__
                    await self.app(scope, receive, inner_send)
                  File "/app/backend/api/middlewares/request_statistics.py", line 59, in __call__
                    raise exc
                  File "/app/backend/api/middlewares/request_statistics.py", line 57, in __call__
                    await self.app(scope, receive, send_with_inspecting_body)
                  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
                    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
                  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
                    raise exc
                  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
                    await app(scope, receive, sender)
                  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
                    await self.middleware_stack(scope, receive, send)
                  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
                    await route.handle(scope, receive, send)
                  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
                    await self.app(scope, receive, send)
                  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
                    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
                  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
                    raise exc
                  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
                    await app(scope, receive, sender)
                  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
                    response = await func(request)
                  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
                    raise e
                  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
                    raw_response = await run_endpoint_function(
                  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
                    return await dependant.call(**values)
                  File "/app/backend/api/routers/users.py", line 75, in register
                    user = await user_manager.create(user_create, safe=False, request=request)
                  File "/app/backend/api/users.py", line 96, in create
                    user = await self.create_with_user_dict(user_dict, user_setting=user_setting)
                  File "/app/backend/api/users.py", line 101, in create_with_user_dict
                    user_setting = user_setting or UserSettingSchema.default()
                  File "/app/backend/api/schemas/user_schemas.py", line 133, in default
                    openai_web=OpenaiWebSourceSettingSchema.default(),
                  File "/app/backend/api/schemas/user_schemas.py", line 61, in default
                    available_models=[m for m in default_models if m in config.openai_web.available_models],
                  File "/app/backend/api/schemas/user_schemas.py", line 61, in <listcomp>
                    available_models=[m for m in default_models if m in config.openai_web.available_models],
                  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 761, in __getattr__
                    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
                AttributeError: 'OpenaiWebChatGPTSetting' object has no attribute 'available_models'

**Additional context**

**Comment by moeakwak** [comment]
0.4.6修复了
