### ISSUE TITLE
Database Connection Problem

### ISSUE THREAD

**Issue by madpancamo** [moeakwak/chatgpt-web-share#67]
**Version**
Last

**What's your deploying environment?**
- [ ] Docker
- [X] Caddy
- [ ] Other

**Describe the problem**
I installed it with Self Deployment, everything is available. I'm getting an error on the last step. 

**Expected behavior**

**Your config.yaml or other configurations**
Provide your configurations. You may hide your secrets or access tokens.

**Screenshots or running logs**
```
`poetry run python main.py
2023/04/05 13:50:23.407     INFO: [uvicorn.error] Started server process [40205]
2023/04/05 13:50:23.407     INFO: [uvicorn.error] Waiting for application startup.
2023/04/05 13:50:23.410    ERROR: [uvicorn.error] Traceback (most recent call last):
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 283, in _do_get
    return self._create_connection()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 905, in __connect
    with util.safe_reraise():
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 636, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 305, in connect
    await_only(connection),
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/aiosqlite/core.py", line 145, in _connect
    self._connection = await future
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/aiosqlite/core.py", line 110, in run
    result = function()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/aiosqlite/core.py", line 405, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/home/ususus/chatgpt-web-share-main/backend/main.py", line 101, in on_startup
    await create_db_and_tables()
  File "/home/ususus/chatgpt-web-share-main/backend/api/database.py", line 48, in create_db_and_tables
    async with engine.connect() as conn:
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/base.py", line 127, in __aenter__
    return await self.start(is_ctxmanager=True)  # type: ignore
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 221, in start
    await (greenlet_spawn(self.sync_engine.connect))
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 165, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3251, in connect
    return self._connection_cls(self)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2413, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
    return self.pool.connect()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 283, in _do_get
    return self._create_connection()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 905, in __connect
    with util.safe_reraise():
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 636, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 580, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 305, in connect
    await_only(connection),
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/aiosqlite/core.py", line 145, in _connect
    self._connection = await future
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/aiosqlite/core.py", line 110, in run
    result = function()
  File "/home/ususus/chatgpt-web-share-main/myenv/lib/python3.10/site-packages/aiosqlite/core.py", line 405, in connector
    return sqlite3.connect(loc, **kwargs)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

2023/04/05 13:50:23.411    ERROR: [uvicorn.error] Application startup failed. Exiting.
`
```

**Comment by moeakwak** [comment]
Please check if the database path set in your configuration file is correct and has write permission.

**Comment by madpancamo** [comment]
chatgpt/backend/api/config/config.yaml - lines 4 and 5 look like this:
`data_dir: ./data`
`database_url: "sqlite+aiosqlite:////data/database.db"`

There is no data folder and  *database.db* file in the file you shared. do i have to create it and how do i create it (will it be hollow?)

**Comment by moeakwak** [comment]
The path `sqlite+aiosqlite:////data/database.db` is intended for Docker environments, as it contains four slashes and points to the file at `/data/database.db`. However, this file path may not exist in non-docker environments.

For your case, you should use `sqlite+aiosqlite:///data/database.db`, which contains only three slashes and points to `./data/database.db`.

**Comment by moeakwak** [comment]
And yes, you should create a `./data` folder in your work directory.
